include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - always_declare_return_types
    - avoid_print
    - prefer_final_locals
    - omit_local_variable_types